version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: demodocker-postgres
    environment:
      POSTGRES_DB: DemoDockerDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456x@X
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demodocker-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: demodocker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - demodocker-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demodocker-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword123!
      - ConnectionStrings__DefaultConnection=Host=demodocker-postgres;Port=5432;Database=DemoDockerDb;Username=postgres;Password=123456x@X
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ~/.dotnet/https:/https:ro
    depends_on:
      - postgres
    networks:
      - demodocker-network

networks:
  demodocker-network:
    driver: bridge

volumes:
  postgres_data: 